### PR TITLE
Translated all the dnfdragora zh_TW translation.

### PR DESCRIPTION
**Pull request by pan93412**
Fixed and translated dnfdragora zh_TW translation, and I also merged the new pot file.

### CODE REVIEW

**Comment by yurchor** [comment]
Hi,

First of all, many thanks for your work.

If it's possible, can you join our Transifex team to upload further translations in a consistent way?

https://www.transifex.com/MageiaLinux/mageia/language/zh_TW/

Thanks in advance for your answer.

**Comment by yurchor** [comment]
Oops, you are a team member already... Sorry.

Please upload your translation onto Tx. Thanks.

**Comment by pan93412** [comment]
Ok, but does Transifex allow to upload po file?

**Comment by yurchor** [comment]
Sure. Just click on "dnfdragora" then choose "Upload" item.

I have already done this for you (look at the last commits in our repo). ;)

**Comment by pan93412** [comment]
Thank u, I see translation in transifex. Thank you a lot <3

Yuri Chornoivan <notifications@github.com> 於 2018年4月23日 週一 下午6:04 寫道：

**Pull request closed without merging**
