### PR TITLE
Update translation catalog

### PR DESCRIPTION
**Pull request by gostsdmitry**
Updated translations into Simplified Chinese (China) and Traditional Chinese (Taiwan) languages.

### CODE REVIEW

**Comment by yurchor** [comment]
Hi!

Can you use our standard way (Transifex [1]) to commit these translations? What is the source of these translations, btw?

Thanks in advance for your answers.

[1] https://www.transifex.com/MageiaLinux/mageia/dnfdragora/

**Comment by gostsdmitry** [comment]
> Hi!
> 
> Can you use our standard way (Transifex [1]) to commit these translations? What is the source of these translations, btw?
> 
> Thanks in advance for your answers.

In principle, I can. The source is the untranslated files themselves.

**Comment by gostsdmitry** [comment]
> https://www.transifex.com/MageiaLinux/mageia/dnfdragora/

At this link error: 404.

**Comment by yurchor** [comment]
> > https://www.transifex.com/MageiaLinux/mageia/dnfdragora/
> 
> At this link error: 404.

Ok (works for me, but anyway). Can you join the teams and upload translations there?

https://www.transifex.com/MageiaLinux/mageia/language/zh_CN/

https://www.transifex.com/MageiaLinux/mageia/language/zh_TW/

That would be much more easier for me to control. Thanks in advance for your work.

**Comment by gostsdmitry** [comment]
> Ok (works for me, but anyway). Can you join the teams and upload translations there?

I sent an application.

**Comment by yurchor** [comment]
> > Ok (works for me, but anyway). Can you join the teams and upload translations there?
> 
> I sent an application.

Accepted.

**Pull request closed without merging**
