### PR TITLE
The translation was a little bit poor

### PR DESCRIPTION
**Pull request by hmikihth**
The translation was a little bit poor. I think Gergely used Google translator in several cases which unfortunatelly doesn't work well with the Hungarian language.

Best Regards,
The blackPanther OS developer team

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
Thanks for submitting translation improvements!

However, translations for dnfdragora are managed through the Mageia Transifex: https://www.transifex.com/MageiaLinux/mageia/dnfdragora/

**Comment by yurchor** [comment]
Miklos is now added to the Hungarian team. He can submit the changes directly or after some discussion in the team. As soon as the new translation is ready I will commit it to the repo ASAP.

Thanks for your notes (and of course for the patch) on the translation.

**Comment by anaselli** [comment]
great job! thanks to all

**Comment by Conan-Kudo** [comment]
@yurchor @hmikihth Is it okay to close out this PR then?

**Comment by hmikihth** [comment]
@anaselli You are wellcome :)

**Comment by hmikihth** [comment]
@Conan-Kudo Yes, I am ging to close it. The new translation is on the Transifex.

**Comment by hmikihth** [comment]
@yurchor I created a new translation for the support page on your web site because the current translation is horrible. For example they write it to there: 

"A Mageia.Org nem támogatja a kereskedelmi, szakmai és más disztribúciókat. De bizonyos szervezetek támogatják a kereskedelmi disztribúciókat."

It means:

"The Mageia.Org don't support the commercial, professional and other distributions. But such organizations support the commercial distributions"

I think the Linux distributons are not each other's enemies, so you don't want to see this horrible translation there :D

**Comment by yurchor** [comment]
@hmikihth Done. Many thanks for your work.

I have escalated your permissions to the reviewer. It would be good for us all if you can review the bad or inappropriate Hungarian translations.

Many thanks in advance for your work.

**Comment by hmikihth** [comment]
Thanks for the permission. I think I forgot to upload the translation of the support-page, but now that is also on the transifex :)

**Comment by yurchor** [comment]
Uploaded to the site.

**Comment by yurchor** [comment]
Please update manatools translation as well. Thanks.

**Comment by hmikihth** [comment]
@yurchor Somebody taken away the reviewer permission from me today. Could you give me back please? Thanks

**Comment by yurchor** [comment]
@hmikihth That was Laszlo Espadas: https://www.transifex.com/user/profile/laszlo.espadas/

I do not know why he has done this. Can you ask him ("Send message" button) to give the permissions back?

I do not know Hungarian enough to moderate this discussion, but can you come to some agreement inside your team without external intrusions?

Thanks for your patience.

**Comment by hmikihth** [comment]
@yurchor I think it is just a personal conflict. He was a member of the blackPanther OS team too but he had a conflict with Charles because he thought Laszlo  has given informations from our secret facebook group to those persons who attacked the blackPanther OS in several forums (for example hup.hu) and facebook groups. But I never had conflicts with Laszlo we talked in a friendly manner every times before that point. And yesterday night we had a short but friendly conversation on the facebook. So I think he just simply doesn't trust in me because I am a blackPanther OS developer, and he doesn't like this distro since that point.
It depends on you if you are happy to see contributions from the blackPanther OS team, please talk about it with Laszlo. 
I think there is no place for the personal conflicts in the open source developments. I prefer collaboration instead of hostility.

**Pull request closed without merging**
