### PR TITLE
Russian translation update

### PR DESCRIPTION
**Pull request by alexmalykh**
Hello there. Please consider updating Russian translation. It is interface-aware, i.e. the strings are translated with surrounding interface context taken into account.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
Could you please submit translations through our Transifex project?

**Comment by alexmalykh** [comment]
Probably, yes. Is there a way to upload the whole .po file on Transifex?

**Comment by yurchor** [comment]
> Probably, yes. Is there a way to upload the whole .po file on Transifex?

Sure. It is here

https://app.transifex.com/MageiaLinux/mageia/dnfdragora/

**Comment by alexmalykh** [comment]
Ok, thanks. I'll try to upload when the join request is approved.

**Comment by yurchor** [comment]
> Ok, thanks. I'll try to upload when the team join request is approved.

Approved.

**Comment by alexmalykh** [comment]
Done. Now we can close the PR, I think.

**Pull request closed without merging**
