### PR TITLE
Add info window and fixed segfault

### PR DESCRIPTION
**Pull request by norby4ever**
There was no information after finishing packages install. Users asked to add an info window at the end of the transaction, so it was added.
There also appeared Segfault error while users were trying to find package with no description. The problem was fixed with the output of an empty line instead of a package description.

### CODE REVIEW

**Comment by anaselli** [comment]
The code is cleaned and easy to read so i can say it's ok for me. Anyway is a dialog at the end of a good transaction really asked by users? 
In rpmdrake we had once but it's been removed time ago since it was "chatty". Mistakes apart a transaction error should be reported by a dialog already, i didn't think to the need of a good one...

**Comment by norby4ever** [comment]
The users couldn't understand when the process of packages installing finished and were angry with the tech support team because of not having any information on the time when the installation was finished. Having received a number of such requests, we decided to add this window.

**Comment by anaselli** [comment]
Pretty odd, I didn't add it as said because it was removed into thje tool inspired me :) But I'm not against it I'm happy to have contributors and also if users use dnfdragora ;) 
Please add you into AUTHORS as contributor, then i'll approve your changes and do a new tag by the ond of this week.
Thank you

**Review by Conan-Kudo — APPROVED** [review]

**Comment by norby4ever** [comment]
Added myself as a contributor, thank you!

**Pull request merged**
