### PR TITLE
Avoid generating multiple notifications.

### PR DESCRIPTION
**Pull request by coreyfarrell**
I've tested this on my workstation.  Ran the new `dnfdragora-updates`, it showed 106 updates.  Without clearing the notification I ran `sudo dnf update -y vim\*` which updated those 4 packages.  3 hours later the notification updated itself to say '102 updates available.'.  Then I ran `sudo dnf update -y` to update the remaining packages.  At the next 3 hours update check dnfdragora-updates removed the notification.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@coreyfarrell Awesome! I'll take a look at it ASAP.

**Comment by anaselli** [comment]
I think @coreyfarrell should also add himself to contributors (maybe AUTHORS file under Contributor?)

**Comment by Conan-Kudo** [comment]
@anaselli Probably yeah. We need a contributors section in there. :)

**Comment by coreyfarrell** [comment]
@anaselli @Conan-Kudo I've amended the commit with the addition to AUTHORS.  Hopefully the formatting is as you were expecting, if not let me know.

**Comment by Conan-Kudo** [comment]
@coreyfarrell Formatting looks great to me!

**Pull request merged**
