### PR TITLE
Add Catalan translation for desktop files

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by yurchor** [comment]
@anaselli No objections to this PR, but is there any better solution for all locales?

**Comment by anaselli** [comment]
@yurchor as for manatools I'm ready to receive and accept any better suggestion or solution :)
Here I haven't managed desktop files yet, honestly :|

**Comment by Conan-Kudo** [comment]
I don't know if there's gettext support for desktop files...

**Comment by yurchor** [comment]
Sure, there is a support for desktop files in gettext.

https://www.gnu.org/software/gettext/manual/gettext.html#Desktop-Entry-mode-operations

And it was implemented by Angelo in manatools. However, here we have a different case...

Can we merge the PR and resolve this issue later?

**Comment by Conan-Kudo** [comment]
Yes. Merging now.

**Comment by Conan-Kudo** [comment]
@yurchor We'll also want to look into supporting translations for our AppStream files (`*.appdata.xml`, `*.metainfo.xml`)

**Comment by yurchor** [comment]
@Conan-Kudo Basically, it is deadly simple. Just add xgettext for XML file into po-update.sh then modify CMakeLists.txt to do "msgfmt --xml -d po --template some.xml.in -o some.xml", but my CMake-fu is rather low and I'm afraid to break something.

I have two working (just tested for dnfdragora) Python scripts, one to extract existing translations from desktop files, and one to merge the translation into desktops (both polib-dependent). Should I send them for testing (maybe as a PR) or is it better (surely it is better, but my bad CMake-fu again...) to adopt .desktop.in/.desktop approach from the pure gettext?

**Comment by Conan-Kudo** [comment]
@yurchor Feel free to send a PR, then it can be reviewed. :)

**Pull request merged**
