### PR TITLE
Use XDG_APPS_INSTALL_DIR & ICON_INSTALL_DIR if available

### PR DESCRIPTION
**Pull request by rbuj**
https://techbase.kde.org/Development/CMake/Addons_for_KDE

### CODE REVIEW

**Comment by rbuj** [comment]
OK ;-)

**Comment by Conan-Kudo** [comment]
I don't mind using KDE's `extra-cmake-modules`, but I need to know how to use them :)

**Comment by anaselli** [comment]
hmm but iiuc the patch was working either if the XDG_APPS_INSTALL_DIR & ICON_INSTALL_DIR macros where defined or not, so maybe it could be accepted anyway no?

**Comment by Conan-Kudo** [comment]
@anaselli Possibly. I tend to not want to vendor in definitions if I don't have to, because if they change, we have to know about it and adapt. Of course, this is not better as-is, either, but eh...

**Pull request closed without merging**
