### PR TITLE
Refresh application icon

### PR DESCRIPTION
**Pull request by pontaoski**
org mageia dnfdragora

### CODE REVIEW

**Comment by anaselli** [comment]
Thanks for your effort and i must confess that compared to our original logo this is much better even if different. As you can figure there a but though...

1. Why **org.mageia.dnfdragora**? dnfdragora is meant to be a cross distro tool, the common points are python, libyui and dnf.
2. As far as I could i avoided _"written in the stone paths"_. I know libyui has something to avoid that but i wasn't really able to use it, and that's why I used **images_path** attribute instead. A better theme (either for Gtk or Qt) management would be great.

For what concern point 2 I'm always open to discuss, so I'm waiting for your reply, but what i prefer is to add absolute path into system settings (maybe over-writeable in user settings for developers), because with your changes, the feature to test icons and logo using the following option is broken:

` --images-path         - local icons and images (set to $DNFDRAGORA_PROJ_DIR/venv/share/dnfdragora/images/)
`

**Comment by pontaoski** [comment]
1) Just following the appstream RDNS notation used by the appdata files. Modern icon tooling expects that you use RDNS notation.
2) Apparently libyui is supposed to be able to pull from the icon theme, but I haven't been able to get that working.

**Comment by anaselli** [comment]
For what concerns point 1, if @Conan-Kudo agrees i havn't objections. We don't have a domain otherwhise something containing manatools would be better.
As far as second point concerns i believe it should work for both theme using (in libyui) or absolute path passing. That's my opinion of course, @Conan-Kudo wdyt? @pontaoski could you review your commits in the case?

**Comment by Conan-Kudo** [comment]
I'm in agreement with @anaselli.

One day, we should grab manatools.org...

**Comment by pontaoski** [comment]
> @pontaoski could you review your commits in the case?

Sorry, I don't understand what you want me to do.

**Comment by anaselli** [comment]
Adding something that checks if the logo or icon exists into hardcoded path into code or looking for it into the given one as for any other images.
I would like to manage all as theme, so one can change all the icons, that could be an option too. But you should also add a way to test all locally, without the need of installing things on the system.

**Comment by Conan-Kudo** [comment]
@pontaoski the commit message doesn't make any sense, please fix it 😄

**Comment by anaselli** [comment]
commit message apart (i didn't look at it) the code seems ok (just changed icons) to me.
I experienced libyui Qt plugin still load the system (or nothing if dnfdragora is  uninstalled) one, but that is not a problem caused by this commit.

**Pull request merged**
